[package]
name = "wlink"
version = "0.0.1"
edition = "2021"
authors = ["Andelf <andelf@gmail.com>"]
repository = "https://github.com/ch32-rs/wlink"
documentation = "https://docs.rs/wlink"
homepage = "https://github.com/ch32-rs/wlink"
categories = ["embedded", "hardware-support", "development-tools::debugging"]
description = "WCH-Link tool for CH32V faimily MCUs(WIP)"
keywords = ["embedded", "WCH", "CH32V", "WCH-Link"]
readme = "README.md"
license = "MIT/Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
bitfield = "0.14.0"
clap = { version = "4", features = ["derive"] }
hex = "0.4.3"
log = "0.4.17"
nu-pretty-hex = "0.76.0"
rusb = "0.9.1"
simplelog = "0.12.0"
thiserror = "1.0.38"
